### ISSUE TITLE
add icon

### ISSUE THREAD

**Issue by FreeVB** [lemutec/NotifyIconEx#1]
How do I add icons to each menu item? Is it possible to implement submenus?

**Comment by emako** [comment]
https://www.nuget.org/packages/NotifyIconEx/1.0.2

**Comment by emako** [comment]
![image](https://github.com/user-attachments/assets/a4b8009f-bbbc-4f69-8edb-a82620268756)

https://www.nuget.org/packages/NotifyIconEx/1.0.4

**Comment by FreeVB** [comment]
Thank you! The test was successful.
In Notifikorn. Admenu ("Exit", (_,_)=>
{
    Notifikorn Dispos ();
    Aplication. Exit ();
}); Add a line, Notificoen, Dispos (); This allows you to clear the icons in the tray when you exit.

**Comment by FreeVB** [comment]
Also, the height of the menu item is relatively small now, is there any way to specify the height?
if (notifyIcon.ContextMenuStrip != null)
{
    notifyIcon.ContextMenuStrip.Font = new Font("Microsoft Yahei", 16F);

This can only set the font size, but not the height of the menu item, which will make the menu item look more beautiful and easy to manipulate.

**Comment by FreeVB** [comment]
private Font _IconMenuFont= new Font("Arial", 16F);
public Font IconMenuFont
{
    get => notifyIcon.ContextMenuStrip!.Font;
    set => _IconMenuFont=value;
}
private void ProcessContextMenuStrip()
{
    if (notifyIcon.ContextMenuStrip == null)
    {
        return;
    }
    notifyIcon.ContextMenuStrip.Font = _IconMenuFont;
    OnContextMenuStripHandleCreated(notifyIcon.ContextMenuStrip, EventArgs.Empty);
    notifyIcon.ContextMenuStrip.Renderer = toolStripRenderer;
    notifyIcon.ContextMenuStrip.HandleCreated += OnContextMenuStripHandleCreated;
}
I've set the menu item font to an attribute to make it more convenient.

**Comment by FreeVB** [comment]
public int IconMenuItemHeight { get; set; } = 6;
public void UpdateStyle()
{
    if (notifyIcon.ContextMenuStrip == null)
    {
        return;
    }

    for (int i = 0; i < notifyIcon.ContextMenuStrip.Items.Count; i++)
    {
        notifyIcon.ContextMenuStrip!.Items[i].Margin = new Padding(0, IconMenuItemHeight, 0, IconMenuItemHeight);
    }
    //UpdatePadding(notifyIcon.ContextMenuStrip.Items);
    notifyIcon.ContextMenuStrip.Opening -= OnContextMenuStripOpening;
    notifyIcon.ContextMenuStrip.Opening += OnContextMenuStripOpening;
    notifyIcon.ContextMenuStrip.BackColor = NotifyIconColors.BackColor;
    notifyIcon.ContextMenuStrip.ForeColor = NotifyIconColors.ForeColor;
    notifyIcon.ContextMenuStrip.Invalidate();
}

That's how I achieved it, looking forward to a better way for @emako , thank you for your reply.

**Comment by FreeVB** [comment]
Fixed the possibility of setting the height of submenu items at the same time.
```
public void UpdateStyle()
{
    if (notifyIcon.ContextMenuStrip == null)
    {
        return;
    }

    AdjustMenuItemMargins(notifyIcon.ContextMenuStrip.Items, IconMenuItemHeight);
    //UpdatePadding(notifyIcon.ContextMenuStrip.Items);
    notifyIcon.ContextMenuStrip.Opening -= OnContextMenuStripOpening;
    notifyIcon.ContextMenuStrip.Opening += OnContextMenuStripOpening;
    notifyIcon.ContextMenuStrip.BackColor = NotifyIconColors.BackColor;
    notifyIcon.ContextMenuStrip.ForeColor = NotifyIconColors.ForeColor;
    notifyIcon.ContextMenuStrip.Invalidate();
}
void AdjustMenuItemMargins(ToolStripItemCollection items, int topBottomMargin)
{
    foreach (ToolStripItem item in items)
    {
        // 检查是否为 ToolStripMenuItem 类型
        if (item is ToolStripMenuItem menuItem)
        {
            // 设置 ToolStripMenuItem 的 Margin
            menuItem.Margin = new Padding(0, topBottomMargin, 0, topBottomMargin);
            // 如果当前菜单项有子菜单项，递归调用此方法
            if (menuItem.HasDropDownItems)
            {
                AdjustMenuItemMargins(menuItem.DropDownItems, topBottomMargin);
            }
        }
        // 如果是 ToolStripSeparator 类型，则不需要设置 Margin，可以忽略或添加其他逻辑
        else if (item is ToolStripSeparator)
        {
            // 这里可以添加对分隔符的处理逻辑，如果需要的话
        }
    }
}
```
