### ISSUE TITLE
MenuFont

### ISSUE THREAD

**Issue by FreeVB** [lemutec/NotifyIconEx#2]
The new property MenuFont prompts an error during testing: System NullReferenceException:“Object reference not set to an instance of an object.”
System. Windows. Forms. NotifyIcon. ContextMenuStrip.get returns null.

**Comment by emako** [comment]
fix that MenuFont can be used after ctor

![image](https://github.com/user-attachments/assets/8bba2f88-615f-4003-b921-b75ee837675a)

**Comment by emako** [comment]
https://www.nuget.org/packages/NotifyIconEx/1.0.6
